### ISSUE TITLE
In BBWIN 0.13 stats.dll sometimes crashes on Windows Server 2019 and 2022

### ISSUE THREAD

**Issue by nafetsa** [multiOTP/bbwin#1]
Any chance that someone can fix BBWIN sometimes crashing on newer Windows Server versions? I'm using version 0.13 and it sometimes stops on several of my newer servers, due to some fault in stats.dll. It sometimes works fine for weeks, and than suddenly everything goes purple. A service restart solves it. I disabled stats.dll on some servers, but on several servers this is no option because I need to check ports.

Faulting application name: BBWin.exe, version: 0.13.0.237, time stamp: 0x4f273487
Faulting module name: stats.dll, version: 0.13.0.237, time stamp: 0x4f27347c
Exception code: 0xc0000005
Fault offset: 0x0000d1c6
Faulting process id: 0x1f98
Faulting application start time: 0x01da60d734c7afc5
Faulting application path: C:\Program Files (x86)\BBWin\bin\BBWin.exe
Faulting module path: C:\Program Files (x86)\BBWin\bin\stats.dll
Report Id: 5784a0d8-5d75-4dfb-99ab-3f47545181b7
Faulting package full name: 
Faulting package-relative application ID:

**Comment by multiOTP** [comment]
Hello,

The source is available here as a mirror of the original site, but we don't develop nor support BBwin on our side.

Regards,
